CREATE TABLE [dbo].[x360ce_PadSettings] (
    [PadSettingChecksum]      UNIQUEIDENTIFIER NOT NULL,
    [AxisToDPadDeadZone]      VARCHAR (16)     NOT NULL,
    [AxisToDPadEnabled]       VARCHAR (16)     NOT NULL,
    [AxisToDPadOffset]        VARCHAR (16)     NOT NULL,
    [ButtonA]                 VARCHAR (16)     NOT NULL,
    [ButtonB]                 VARCHAR (16)     NOT NULL,
    [ButtonBack]              VARCHAR (16)     NOT NULL,
    [ButtonStart]             VARCHAR (16)     NOT NULL,
    [ButtonX]                 VARCHAR (16)     NOT NULL,
    [ButtonY]                 VARCHAR (16)     NOT NULL,
    [DPad]                    VARCHAR (16)     NOT NULL,
    [DPadDown]                VARCHAR (16)     NOT NULL,
    [DPadLeft]                VARCHAR (16)     NOT NULL,
    [DPadRight]               VARCHAR (16)     NOT NULL,
    [DPadUp]                  VARCHAR (16)     NOT NULL,
    [ForceEnable]             VARCHAR (16)     NOT NULL,
    [ForceOverall]            VARCHAR (16)     NOT NULL,
    [ForceSwapMotor]          VARCHAR (16)     NOT NULL,
    [ForceType]               VARCHAR (16)     NOT NULL,
    [GamePadType]             VARCHAR (16)     NOT NULL,
    [LeftMotorPeriod]         VARCHAR (16)     NOT NULL,
    [LeftShoulder]            VARCHAR (16)     NOT NULL,
    [LeftThumbAntiDeadZoneX]  VARCHAR (16)     NOT NULL,
    [LeftThumbAntiDeadZoneY]  VARCHAR (16)     NOT NULL,
    [LeftThumbAxisX]          VARCHAR (16)     NOT NULL,
    [LeftThumbAxisY]          VARCHAR (16)     NOT NULL,
    [LeftThumbButton]         VARCHAR (16)     NOT NULL,
    [LeftThumbDeadZoneX]      VARCHAR (16)     NOT NULL,
    [LeftThumbDeadZoneY]      VARCHAR (16)     NOT NULL,
    [LeftThumbDown]           VARCHAR (16)     NOT NULL,
    [LeftThumbLeft]           VARCHAR (16)     NOT NULL,
    [LeftThumbRight]          VARCHAR (16)     NOT NULL,
    [LeftThumbUp]             VARCHAR (16)     NOT NULL,
    [LeftTrigger]             VARCHAR (16)     NOT NULL,
    [LeftTriggerDeadZone]     VARCHAR (16)     NOT NULL,
    [PassThrough]             VARCHAR (16)     NOT NULL,
    [RightMotorPeriod]        VARCHAR (16)     NOT NULL,
    [RightShoulder]           VARCHAR (16)     NOT NULL,
    [RightThumbAntiDeadZoneX] VARCHAR (16)     NOT NULL,
    [RightThumbAntiDeadZoneY] VARCHAR (16)     NOT NULL,
    [RightThumbAxisX]         VARCHAR (16)     NOT NULL,
    [RightThumbAxisY]         VARCHAR (16)     NOT NULL,
    [RightThumbButton]        VARCHAR (16)     NOT NULL,
    [RightThumbDeadZoneX]     VARCHAR (16)     NOT NULL,
    [RightThumbDeadZoneY]     VARCHAR (16)     NOT NULL,
    [RightThumbDown]          VARCHAR (16)     NOT NULL,
    [RightThumbLeft]          VARCHAR (16)     NOT NULL,
    [RightThumbRight]         VARCHAR (16)     NOT NULL,
    [RightThumbUp]            VARCHAR (16)     NOT NULL,
    [RightTrigger]            VARCHAR (16)     NOT NULL,
    [RightTriggerDeadZone]    VARCHAR (16)     NOT NULL
);



