//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace x360ce.App.com.x360ce.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="x360ceSoap", Namespace="http://x360ce.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class x360ce : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVendorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSettingsDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetProgramOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignInOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public x360ce() {
            this.Url = global::x360ce.App.Properties.Settings.Default.x360ce_com_x360ce_localhost_x360ce;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveSettingCompletedEventHandler SaveSettingCompleted;
        
        /// <remarks/>
        public event SearchSettingsCompletedEventHandler SearchSettingsCompleted;
        
        /// <remarks/>
        public event DeleteSettingCompletedEventHandler DeleteSettingCompleted;
        
        /// <remarks/>
        public event LoadSettingCompletedEventHandler LoadSettingCompleted;
        
        /// <remarks/>
        public event GetVendorsCompletedEventHandler GetVendorsCompleted;
        
        /// <remarks/>
        public event GetSettingsDataCompletedEventHandler GetSettingsDataCompleted;
        
        /// <remarks/>
        public event GetProgramsCompletedEventHandler GetProgramsCompleted;
        
        /// <remarks/>
        public event GetProgramCompletedEventHandler GetProgramCompleted;
        
        /// <remarks/>
        public event SetProgramCompletedEventHandler SetProgramCompleted;
        
        /// <remarks/>
        public event SignOutCompletedEventHandler SignOutCompleted;
        
        /// <remarks/>
        public event SignInCompletedEventHandler SignInCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/SaveSetting", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveSetting(Setting s, PadSetting ps) {
            object[] results = this.Invoke("SaveSetting", new object[] {
                        s,
                        ps});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSettingAsync(Setting s, PadSetting ps) {
            this.SaveSettingAsync(s, ps, null);
        }
        
        /// <remarks/>
        public void SaveSettingAsync(Setting s, PadSetting ps, object userState) {
            if ((this.SaveSettingOperationCompleted == null)) {
                this.SaveSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSettingOperationCompleted);
            }
            this.InvokeAsync("SaveSetting", new object[] {
                        s,
                        ps}, this.SaveSettingOperationCompleted, userState);
        }
        
        private void OnSaveSettingOperationCompleted(object arg) {
            if ((this.SaveSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSettingCompleted(this, new SaveSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/SearchSettings", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult SearchSettings(SearchParameter[] args) {
            object[] results = this.Invoke("SearchSettings", new object[] {
                        args});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchSettingsAsync(SearchParameter[] args) {
            this.SearchSettingsAsync(args, null);
        }
        
        /// <remarks/>
        public void SearchSettingsAsync(SearchParameter[] args, object userState) {
            if ((this.SearchSettingsOperationCompleted == null)) {
                this.SearchSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchSettingsOperationCompleted);
            }
            this.InvokeAsync("SearchSettings", new object[] {
                        args}, this.SearchSettingsOperationCompleted, userState);
        }
        
        private void OnSearchSettingsOperationCompleted(object arg) {
            if ((this.SearchSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchSettingsCompleted(this, new SearchSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/DeleteSetting", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteSetting(Setting s) {
            object[] results = this.Invoke("DeleteSetting", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSettingAsync(Setting s) {
            this.DeleteSettingAsync(s, null);
        }
        
        /// <remarks/>
        public void DeleteSettingAsync(Setting s, object userState) {
            if ((this.DeleteSettingOperationCompleted == null)) {
                this.DeleteSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSettingOperationCompleted);
            }
            this.InvokeAsync("DeleteSetting", new object[] {
                        s}, this.DeleteSettingOperationCompleted, userState);
        }
        
        private void OnDeleteSettingOperationCompleted(object arg) {
            if ((this.DeleteSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSettingCompleted(this, new DeleteSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/LoadSetting", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult LoadSetting(System.Guid[] checksum) {
            object[] results = this.Invoke("LoadSetting", new object[] {
                        checksum});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoadSettingAsync(System.Guid[] checksum) {
            this.LoadSettingAsync(checksum, null);
        }
        
        /// <remarks/>
        public void LoadSettingAsync(System.Guid[] checksum, object userState) {
            if ((this.LoadSettingOperationCompleted == null)) {
                this.LoadSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadSettingOperationCompleted);
            }
            this.InvokeAsync("LoadSetting", new object[] {
                        checksum}, this.LoadSettingOperationCompleted, userState);
        }
        
        private void OnLoadSettingOperationCompleted(object arg) {
            if ((this.LoadSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadSettingCompleted(this, new LoadSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/GetVendors", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vendor[] GetVendors() {
            object[] results = this.Invoke("GetVendors", new object[0]);
            return ((Vendor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVendorsAsync() {
            this.GetVendorsAsync(null);
        }
        
        /// <remarks/>
        public void GetVendorsAsync(object userState) {
            if ((this.GetVendorsOperationCompleted == null)) {
                this.GetVendorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVendorsOperationCompleted);
            }
            this.InvokeAsync("GetVendors", new object[0], this.GetVendorsOperationCompleted, userState);
        }
        
        private void OnGetVendorsOperationCompleted(object arg) {
            if ((this.GetVendorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVendorsCompleted(this, new GetVendorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/GetSettingsData", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SettingsData GetSettingsData() {
            object[] results = this.Invoke("GetSettingsData", new object[0]);
            return ((SettingsData)(results[0]));
        }
        
        /// <remarks/>
        public void GetSettingsDataAsync() {
            this.GetSettingsDataAsync(null);
        }
        
        /// <remarks/>
        public void GetSettingsDataAsync(object userState) {
            if ((this.GetSettingsDataOperationCompleted == null)) {
                this.GetSettingsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSettingsDataOperationCompleted);
            }
            this.InvokeAsync("GetSettingsData", new object[0], this.GetSettingsDataOperationCompleted, userState);
        }
        
        private void OnGetSettingsDataOperationCompleted(object arg) {
            if ((this.GetSettingsDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSettingsDataCompleted(this, new GetSettingsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/GetPrograms", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Program[] GetPrograms([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> isEnabled, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> minInstanceCount) {
            object[] results = this.Invoke("GetPrograms", new object[] {
                        isEnabled,
                        minInstanceCount});
            return ((Program[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramsAsync(System.Nullable<bool> isEnabled, System.Nullable<int> minInstanceCount) {
            this.GetProgramsAsync(isEnabled, minInstanceCount, null);
        }
        
        /// <remarks/>
        public void GetProgramsAsync(System.Nullable<bool> isEnabled, System.Nullable<int> minInstanceCount, object userState) {
            if ((this.GetProgramsOperationCompleted == null)) {
                this.GetProgramsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramsOperationCompleted);
            }
            this.InvokeAsync("GetPrograms", new object[] {
                        isEnabled,
                        minInstanceCount}, this.GetProgramsOperationCompleted, userState);
        }
        
        private void OnGetProgramsOperationCompleted(object arg) {
            if ((this.GetProgramsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramsCompleted(this, new GetProgramsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/GetProgram", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Program GetProgram(string fileName, string fileProductName) {
            object[] results = this.Invoke("GetProgram", new object[] {
                        fileName,
                        fileProductName});
            return ((Program)(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramAsync(string fileName, string fileProductName) {
            this.GetProgramAsync(fileName, fileProductName, null);
        }
        
        /// <remarks/>
        public void GetProgramAsync(string fileName, string fileProductName, object userState) {
            if ((this.GetProgramOperationCompleted == null)) {
                this.GetProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramOperationCompleted);
            }
            this.InvokeAsync("GetProgram", new object[] {
                        fileName,
                        fileProductName}, this.GetProgramOperationCompleted, userState);
        }
        
        private void OnGetProgramOperationCompleted(object arg) {
            if ((this.GetProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramCompleted(this, new GetProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/SetProgram", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetProgram(Program p) {
            object[] results = this.Invoke("SetProgram", new object[] {
                        p});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetProgramAsync(Program p) {
            this.SetProgramAsync(p, null);
        }
        
        /// <remarks/>
        public void SetProgramAsync(Program p, object userState) {
            if ((this.SetProgramOperationCompleted == null)) {
                this.SetProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetProgramOperationCompleted);
            }
            this.InvokeAsync("SetProgram", new object[] {
                        p}, this.SetProgramOperationCompleted, userState);
        }
        
        private void OnSetProgramOperationCompleted(object arg) {
            if ((this.SetProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetProgramCompleted(this, new SetProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/SignOut", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KeyValue[] SignOut() {
            object[] results = this.Invoke("SignOut", new object[0]);
            return ((KeyValue[])(results[0]));
        }
        
        /// <remarks/>
        public void SignOutAsync() {
            this.SignOutAsync(null);
        }
        
        /// <remarks/>
        public void SignOutAsync(object userState) {
            if ((this.SignOutOperationCompleted == null)) {
                this.SignOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignOutOperationCompleted);
            }
            this.InvokeAsync("SignOut", new object[0], this.SignOutOperationCompleted, userState);
        }
        
        private void OnSignOutOperationCompleted(object arg) {
            if ((this.SignOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignOutCompleted(this, new SignOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://x360ce.com/SignIn", RequestNamespace="http://x360ce.com/", ResponseNamespace="http://x360ce.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KeyValue[] SignIn(string username, string password) {
            object[] results = this.Invoke("SignIn", new object[] {
                        username,
                        password});
            return ((KeyValue[])(results[0]));
        }
        
        /// <remarks/>
        public void SignInAsync(string username, string password) {
            this.SignInAsync(username, password, null);
        }
        
        /// <remarks/>
        public void SignInAsync(string username, string password, object userState) {
            if ((this.SignInOperationCompleted == null)) {
                this.SignInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignInOperationCompleted);
            }
            this.InvokeAsync("SignIn", new object[] {
                        username,
                        password}, this.SignInOperationCompleted, userState);
        }
        
        private void OnSignInOperationCompleted(object arg) {
            if ((this.SignInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignInCompleted(this, new SignInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class Setting : EntityObject {
        
        private System.Guid settingIdField;
        
        private System.Guid instanceGuidField;
        
        private string instanceNameField;
        
        private System.Guid productGuidField;
        
        private string productNameField;
        
        private int deviceTypeField;
        
        private string fileNameField;
        
        private string fileProductNameField;
        
        private string commentField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateUpdatedField;
        
        private bool isEnabledField;
        
        private System.Guid padSettingChecksumField;
        
        private System.DateTime dateSelectedField;
        
        /// <remarks/>
        public System.Guid SettingId {
            get {
                return this.settingIdField;
            }
            set {
                this.settingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid InstanceGuid {
            get {
                return this.instanceGuidField;
            }
            set {
                this.instanceGuidField = value;
            }
        }
        
        /// <remarks/>
        public string InstanceName {
            get {
                return this.instanceNameField;
            }
            set {
                this.instanceNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ProductGuid {
            get {
                return this.productGuidField;
            }
            set {
                this.productGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string FileProductName {
            get {
                return this.fileProductNameField;
            }
            set {
                this.fileProductNameField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PadSettingChecksum {
            get {
                return this.padSettingChecksumField;
            }
            set {
                this.padSettingChecksumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateSelected {
            get {
                return this.dateSelectedField;
            }
            set {
                this.dateSelectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Program))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PadSetting))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Summary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Setting))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class KeyValue {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class SettingsData {
        
        private Program[] programsField;
        
        /// <remarks/>
        public Program[] Programs {
            get {
                return this.programsField;
            }
            set {
                this.programsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class Program : EntityObject {
        
        private System.Guid programIdField;
        
        private string fileNameField;
        
        private string fileProductNameField;
        
        private int hookMaskField;
        
        private int xInputMaskField;
        
        private int instanceCountField;
        
        private bool isEnabledField;
        
        private System.DateTime dateCreatedField;
        
        private System.Nullable<System.DateTime> dateUpdatedField;
        
        /// <remarks/>
        public System.Guid ProgramId {
            get {
                return this.programIdField;
            }
            set {
                this.programIdField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string FileProductName {
            get {
                return this.fileProductNameField;
            }
            set {
                this.fileProductNameField = value;
            }
        }
        
        /// <remarks/>
        public int HookMask {
            get {
                return this.hookMaskField;
            }
            set {
                this.hookMaskField = value;
            }
        }
        
        /// <remarks/>
        public int XInputMask {
            get {
                return this.xInputMaskField;
            }
            set {
                this.xInputMaskField = value;
            }
        }
        
        /// <remarks/>
        public int InstanceCount {
            get {
                return this.instanceCountField;
            }
            set {
                this.instanceCountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class Vendor {
        
        private int vendorIdField;
        
        private string vendorNameField;
        
        private string shortNameField;
        
        private string webSiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int VendorId {
            get {
                return this.vendorIdField;
            }
            set {
                this.vendorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WebSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class SearchResult {
        
        private Setting[] settingsField;
        
        private Summary[] summariesField;
        
        private PadSetting[] padSettingsField;
        
        /// <remarks/>
        public Setting[] Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public Summary[] Summaries {
            get {
                return this.summariesField;
            }
            set {
                this.summariesField = value;
            }
        }
        
        /// <remarks/>
        public PadSetting[] PadSettings {
            get {
                return this.padSettingsField;
            }
            set {
                this.padSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class Summary : EntityObject {
        
        private System.Guid summaryIdField;
        
        private int usersField;
        
        private System.Guid padSettingChecksumField;
        
        private System.Guid productGuidField;
        
        private string productNameField;
        
        private string fileNameField;
        
        private string fileProductNameField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateUpdatedField;
        
        /// <remarks/>
        public System.Guid SummaryId {
            get {
                return this.summaryIdField;
            }
            set {
                this.summaryIdField = value;
            }
        }
        
        /// <remarks/>
        public int Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PadSettingChecksum {
            get {
                return this.padSettingChecksumField;
            }
            set {
                this.padSettingChecksumField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ProductGuid {
            get {
                return this.productGuidField;
            }
            set {
                this.productGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string FileProductName {
            get {
                return this.fileProductNameField;
            }
            set {
                this.fileProductNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class PadSetting : EntityObject {
        
        private System.Guid padSettingChecksumField;
        
        private string axisToDPadDeadZoneField;
        
        private string axisToDPadEnabledField;
        
        private string axisToDPadOffsetField;
        
        private string buttonAField;
        
        private string buttonBField;
        
        private string buttonBigField;
        
        private string buttonBackField;
        
        private string buttonGuideField;
        
        private string buttonStartField;
        
        private string buttonXField;
        
        private string buttonYField;
        
        private string dPadField;
        
        private string dPadDownField;
        
        private string dPadLeftField;
        
        private string dPadRightField;
        
        private string dPadUpField;
        
        private string forceEnableField;
        
        private string forceOverallField;
        
        private string forceSwapMotorField;
        
        private string forceTypeField;
        
        private string gamePadTypeField;
        
        private string leftMotorPeriodField;
        
        private string leftShoulderField;
        
        private string leftThumbAntiDeadZoneXField;
        
        private string leftThumbAntiDeadZoneYField;
        
        private string leftThumbAxisXField;
        
        private string leftThumbAxisYField;
        
        private string leftThumbButtonField;
        
        private string leftThumbDeadZoneXField;
        
        private string leftThumbDeadZoneYField;
        
        private string leftThumbDownField;
        
        private string leftThumbLeftField;
        
        private string leftThumbRightField;
        
        private string leftThumbUpField;
        
        private string leftTriggerField;
        
        private string leftTriggerDeadZoneField;
        
        private string passThroughField;
        
        private string rightMotorPeriodField;
        
        private string rightShoulderField;
        
        private string rightThumbAntiDeadZoneXField;
        
        private string rightThumbAntiDeadZoneYField;
        
        private string rightThumbAxisXField;
        
        private string rightThumbAxisYField;
        
        private string rightThumbButtonField;
        
        private string rightThumbDeadZoneXField;
        
        private string rightThumbDeadZoneYField;
        
        private string rightThumbDownField;
        
        private string rightThumbLeftField;
        
        private string rightThumbRightField;
        
        private string rightThumbUpField;
        
        private string rightTriggerField;
        
        private string rightTriggerDeadZoneField;
        
        /// <remarks/>
        public System.Guid PadSettingChecksum {
            get {
                return this.padSettingChecksumField;
            }
            set {
                this.padSettingChecksumField = value;
            }
        }
        
        /// <remarks/>
        public string AxisToDPadDeadZone {
            get {
                return this.axisToDPadDeadZoneField;
            }
            set {
                this.axisToDPadDeadZoneField = value;
            }
        }
        
        /// <remarks/>
        public string AxisToDPadEnabled {
            get {
                return this.axisToDPadEnabledField;
            }
            set {
                this.axisToDPadEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string AxisToDPadOffset {
            get {
                return this.axisToDPadOffsetField;
            }
            set {
                this.axisToDPadOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonA {
            get {
                return this.buttonAField;
            }
            set {
                this.buttonAField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonB {
            get {
                return this.buttonBField;
            }
            set {
                this.buttonBField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonBig {
            get {
                return this.buttonBigField;
            }
            set {
                this.buttonBigField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonBack {
            get {
                return this.buttonBackField;
            }
            set {
                this.buttonBackField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonGuide {
            get {
                return this.buttonGuideField;
            }
            set {
                this.buttonGuideField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonStart {
            get {
                return this.buttonStartField;
            }
            set {
                this.buttonStartField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonX {
            get {
                return this.buttonXField;
            }
            set {
                this.buttonXField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonY {
            get {
                return this.buttonYField;
            }
            set {
                this.buttonYField = value;
            }
        }
        
        /// <remarks/>
        public string DPad {
            get {
                return this.dPadField;
            }
            set {
                this.dPadField = value;
            }
        }
        
        /// <remarks/>
        public string DPadDown {
            get {
                return this.dPadDownField;
            }
            set {
                this.dPadDownField = value;
            }
        }
        
        /// <remarks/>
        public string DPadLeft {
            get {
                return this.dPadLeftField;
            }
            set {
                this.dPadLeftField = value;
            }
        }
        
        /// <remarks/>
        public string DPadRight {
            get {
                return this.dPadRightField;
            }
            set {
                this.dPadRightField = value;
            }
        }
        
        /// <remarks/>
        public string DPadUp {
            get {
                return this.dPadUpField;
            }
            set {
                this.dPadUpField = value;
            }
        }
        
        /// <remarks/>
        public string ForceEnable {
            get {
                return this.forceEnableField;
            }
            set {
                this.forceEnableField = value;
            }
        }
        
        /// <remarks/>
        public string ForceOverall {
            get {
                return this.forceOverallField;
            }
            set {
                this.forceOverallField = value;
            }
        }
        
        /// <remarks/>
        public string ForceSwapMotor {
            get {
                return this.forceSwapMotorField;
            }
            set {
                this.forceSwapMotorField = value;
            }
        }
        
        /// <remarks/>
        public string ForceType {
            get {
                return this.forceTypeField;
            }
            set {
                this.forceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GamePadType {
            get {
                return this.gamePadTypeField;
            }
            set {
                this.gamePadTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LeftMotorPeriod {
            get {
                return this.leftMotorPeriodField;
            }
            set {
                this.leftMotorPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string LeftShoulder {
            get {
                return this.leftShoulderField;
            }
            set {
                this.leftShoulderField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbAntiDeadZoneX {
            get {
                return this.leftThumbAntiDeadZoneXField;
            }
            set {
                this.leftThumbAntiDeadZoneXField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbAntiDeadZoneY {
            get {
                return this.leftThumbAntiDeadZoneYField;
            }
            set {
                this.leftThumbAntiDeadZoneYField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbAxisX {
            get {
                return this.leftThumbAxisXField;
            }
            set {
                this.leftThumbAxisXField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbAxisY {
            get {
                return this.leftThumbAxisYField;
            }
            set {
                this.leftThumbAxisYField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbButton {
            get {
                return this.leftThumbButtonField;
            }
            set {
                this.leftThumbButtonField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbDeadZoneX {
            get {
                return this.leftThumbDeadZoneXField;
            }
            set {
                this.leftThumbDeadZoneXField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbDeadZoneY {
            get {
                return this.leftThumbDeadZoneYField;
            }
            set {
                this.leftThumbDeadZoneYField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbDown {
            get {
                return this.leftThumbDownField;
            }
            set {
                this.leftThumbDownField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbLeft {
            get {
                return this.leftThumbLeftField;
            }
            set {
                this.leftThumbLeftField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbRight {
            get {
                return this.leftThumbRightField;
            }
            set {
                this.leftThumbRightField = value;
            }
        }
        
        /// <remarks/>
        public string LeftThumbUp {
            get {
                return this.leftThumbUpField;
            }
            set {
                this.leftThumbUpField = value;
            }
        }
        
        /// <remarks/>
        public string LeftTrigger {
            get {
                return this.leftTriggerField;
            }
            set {
                this.leftTriggerField = value;
            }
        }
        
        /// <remarks/>
        public string LeftTriggerDeadZone {
            get {
                return this.leftTriggerDeadZoneField;
            }
            set {
                this.leftTriggerDeadZoneField = value;
            }
        }
        
        /// <remarks/>
        public string PassThrough {
            get {
                return this.passThroughField;
            }
            set {
                this.passThroughField = value;
            }
        }
        
        /// <remarks/>
        public string RightMotorPeriod {
            get {
                return this.rightMotorPeriodField;
            }
            set {
                this.rightMotorPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string RightShoulder {
            get {
                return this.rightShoulderField;
            }
            set {
                this.rightShoulderField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbAntiDeadZoneX {
            get {
                return this.rightThumbAntiDeadZoneXField;
            }
            set {
                this.rightThumbAntiDeadZoneXField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbAntiDeadZoneY {
            get {
                return this.rightThumbAntiDeadZoneYField;
            }
            set {
                this.rightThumbAntiDeadZoneYField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbAxisX {
            get {
                return this.rightThumbAxisXField;
            }
            set {
                this.rightThumbAxisXField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbAxisY {
            get {
                return this.rightThumbAxisYField;
            }
            set {
                this.rightThumbAxisYField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbButton {
            get {
                return this.rightThumbButtonField;
            }
            set {
                this.rightThumbButtonField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbDeadZoneX {
            get {
                return this.rightThumbDeadZoneXField;
            }
            set {
                this.rightThumbDeadZoneXField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbDeadZoneY {
            get {
                return this.rightThumbDeadZoneYField;
            }
            set {
                this.rightThumbDeadZoneYField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbDown {
            get {
                return this.rightThumbDownField;
            }
            set {
                this.rightThumbDownField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbLeft {
            get {
                return this.rightThumbLeftField;
            }
            set {
                this.rightThumbLeftField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbRight {
            get {
                return this.rightThumbRightField;
            }
            set {
                this.rightThumbRightField = value;
            }
        }
        
        /// <remarks/>
        public string RightThumbUp {
            get {
                return this.rightThumbUpField;
            }
            set {
                this.rightThumbUpField = value;
            }
        }
        
        /// <remarks/>
        public string RightTrigger {
            get {
                return this.rightTriggerField;
            }
            set {
                this.rightTriggerField = value;
            }
        }
        
        /// <remarks/>
        public string RightTriggerDeadZone {
            get {
                return this.rightTriggerDeadZoneField;
            }
            set {
                this.rightTriggerDeadZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public partial class SearchParameter {
        
        private System.Guid productGuidField;
        
        private System.Guid instanceGuidField;
        
        private string fileNameField;
        
        private string fileProductNameField;
        
        /// <remarks/>
        public System.Guid ProductGuid {
            get {
                return this.productGuidField;
            }
            set {
                this.productGuidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid InstanceGuid {
            get {
                return this.instanceGuidField;
            }
            set {
                this.instanceGuidField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string FileProductName {
            get {
                return this.fileProductNameField;
            }
            set {
                this.fileProductNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Program))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PadSetting))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Summary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Setting))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x360ce.com/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveSettingCompletedEventHandler(object sender, SaveSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchSettingsCompletedEventHandler(object sender, SearchSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteSettingCompletedEventHandler(object sender, DeleteSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoadSettingCompletedEventHandler(object sender, LoadSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetVendorsCompletedEventHandler(object sender, GetVendorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVendorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVendorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vendor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vendor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSettingsDataCompletedEventHandler(object sender, GetSettingsDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSettingsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSettingsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SettingsData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SettingsData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProgramsCompletedEventHandler(object sender, GetProgramsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Program[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Program[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProgramCompletedEventHandler(object sender, GetProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Program Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Program)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetProgramCompletedEventHandler(object sender, SetProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SignOutCompletedEventHandler(object sender, SignOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SignInCompletedEventHandler(object sender, SignInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValue[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591