/* Generated by genrev.cmd from git. Do not edit. */
#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV         2613
#define SVN_REVSTR      "2613"
#define SVN_REVDATE     "2026-08-23"
#define SVN_REVSTAMP    20260823L
#define SVN_REVMODIFIED 1

#endif /* SVN_REV_H */
