namespace JocysCom.ClassLibrary.Win32
{
	/// <summary>
	/// Error codes defined in Cfgmgr32.h:
	/// c:\Program Files\Microsoft SDKs\Windows\v7.1\Include\cfgmgr32.h
	/// </summary>
	public enum CR
	{
		CR_SUCCESS = 0,
		CR_DEFAULT,
		CR_OUT_OF_MEMORY,
		CR_INVALID_POINTER,
		CR_INVALID_FLAG,
		CR_INVALID_DEVNODE,
		CR_INVALID_RES_DES,
		CR_INVALID_LOG_CONF,
		CR_INVALID_ARBITRATOR,
		CR_INVALID_NODELIST,
		CR_DEVNODE_HAS_REQS,
		CR_INVALID_RESOURCEID,
		CR_DLVXD_NOT_FOUND,
		CR_NO_SUCH_DEVNODE, // WIN 95 ONLY
		CR_NO_MORE_LOG_CONF,
		CR_NO_MORE_RES_DES,
		CR_ALREADY_SUCH_DEVNODE,
		CR_INVALID_RANGE_LIST,
		CR_INVALID_RANGE,
		CR_FAILURE,
		CR_NO_SUCH_LOGICAL_DEV,
		CR_CREATE_BLOCKED,
		CR_NOT_SYSTEM_VM,
		CR_REMOVE_VETOED, // WIN 95 ONLY
		CR_APM_VETOED,
		CR_INVALID_LOAD_TYPE,
		CR_BUFFER_SMALL,
		CR_NO_ARBITRATOR,
		CR_NO_REGISTRY_HANDLE,
		CR_REGISTRY_ERROR,
		CR_INVALID_DEVICE_ID,
		CR_INVALID_DATA,
		CR_INVALID_API,
		CR_DEVLOADER_NOT_READY,
		CR_NEED_RESTART,
		CR_NO_MORE_HW_PROFILES,
		CR_DEVICE_NOT_THERE,
		CR_NO_SUCH_VALUE,
		CR_WRONG_TYPE,
		CR_INVALID_PRIORITY,
		CR_NOT_DISABLEABLE,
		CR_FREE_RESOURCES,
		CR_QUERY_VETOED,
		CR_CANT_SHARE_IRQ,
		CR_NO_DEPENDENT,
		CR_SAME_RESOURCES,
		CR_NO_SUCH_REGISTRY_KEY,
		CR_INVALID_MACHINENAME,
		CR_REMOTE_COMM_FAILURE,  // NT ONLY
		CR_MACHINE_UNAVAILABLE,  // NT ONLY
		CR_NO_CM_SERVICES,       // NT ONLY
		CR_ACCESS_DENIED,        // NT ONLY
		CR_CALL_NOT_IMPLEMENTED, // NT ONLY
		CR_INVALID_PROPERTY,
		CR_DEVICE_INTERFACE_ACTIVE,
		CR_NO_SUCH_DEVICE_INTERFACE,
		CR_INVALID_REFERENCE_STRING,
		CR_INVALID_CONFLICT_LIST,
		CR_INVALID_INDEX,
		CR_INVALID_STRUCTURE_SIZE,
		NUM_CR_RESULTS
	}
}
