//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace JocysCom.ClassLibrary.Resources.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ResourcesModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ResourcesModelContainer object using the connection string found in the 'ResourcesModelContainer' section of the application configuration file.
        /// </summary>
        public ResourcesModelContainer() : base("name=ResourcesModelContainer", "ResourcesModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResourcesModelContainer object.
        /// </summary>
        public ResourcesModelContainer(string connectionString) : base(connectionString, "ResourcesModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResourcesModelContainer object.
        /// </summary>
        public ResourcesModelContainer(EntityConnection connection) : base(connection, "ResourcesModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Setting setting)
        {
            base.AddObject("Settings", setting);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JocysCom.ClassLibrary.Resources.Data", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cultureCode">Initial value of the CultureCode property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="section">Initial value of the Section property.</param>
        /// <param name="keyType">Initial value of the KeyType property.</param>
        /// <param name="keyName">Initial value of the KeyName property.</param>
        /// <param name="keyValue">Initial value of the KeyValue property.</param>
        /// <param name="replacement">Initial value of the Replacement property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="isExpression">Initial value of the IsExpression property.</param>
        /// <param name="isSerialized">Initial value of the IsSerialized property.</param>
        /// <param name="isEnabled">Initial value of the IsEnabled property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateUpdated">Initial value of the DateUpdated property.</param>
        public static Setting CreateSetting(global::System.Guid id, global::System.String cultureCode, global::System.String category, global::System.String section, global::System.String keyType, global::System.String keyName, global::System.String keyValue, global::System.String replacement, global::System.String description, global::System.Boolean isExpression, global::System.Boolean isSerialized, global::System.Boolean isEnabled, global::System.DateTime dateCreated, global::System.DateTime dateUpdated)
        {
            Setting setting = new Setting();
            setting.Id = id;
            setting.CultureCode = cultureCode;
            setting.Category = category;
            setting.Section = section;
            setting.KeyType = keyType;
            setting.KeyName = keyName;
            setting.KeyValue = keyValue;
            setting.Replacement = replacement;
            setting.Description = description;
            setting.IsExpression = isExpression;
            setting.IsSerialized = isSerialized;
            setting.IsEnabled = isEnabled;
            setting.DateCreated = dateCreated;
            setting.DateUpdated = dateUpdated;
            return setting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CultureCode
        {
            get
            {
                return _CultureCode;
            }
            set
            {
                OnCultureCodeChanging(value);
                ReportPropertyChanging("CultureCode");
                _CultureCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CultureCode");
                OnCultureCodeChanged();
            }
        }
        private global::System.String _CultureCode;
        partial void OnCultureCodeChanging(global::System.String value);
        partial void OnCultureCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Section
        {
            get
            {
                return _Section;
            }
            set
            {
                OnSectionChanging(value);
                ReportPropertyChanging("Section");
                _Section = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Section");
                OnSectionChanged();
            }
        }
        private global::System.String _Section;
        partial void OnSectionChanging(global::System.String value);
        partial void OnSectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KeyType
        {
            get
            {
                return _KeyType;
            }
            set
            {
                OnKeyTypeChanging(value);
                ReportPropertyChanging("KeyType");
                _KeyType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KeyType");
                OnKeyTypeChanged();
            }
        }
        private global::System.String _KeyType;
        partial void OnKeyTypeChanging(global::System.String value);
        partial void OnKeyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KeyName
        {
            get
            {
                return _KeyName;
            }
            set
            {
                OnKeyNameChanging(value);
                ReportPropertyChanging("KeyName");
                _KeyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KeyName");
                OnKeyNameChanged();
            }
        }
        private global::System.String _KeyName;
        partial void OnKeyNameChanging(global::System.String value);
        partial void OnKeyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KeyValue
        {
            get
            {
                return _KeyValue;
            }
            set
            {
                OnKeyValueChanging(value);
                ReportPropertyChanging("KeyValue");
                _KeyValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KeyValue");
                OnKeyValueChanged();
            }
        }
        private global::System.String _KeyValue;
        partial void OnKeyValueChanging(global::System.String value);
        partial void OnKeyValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Replacement
        {
            get
            {
                return _Replacement;
            }
            set
            {
                OnReplacementChanging(value);
                ReportPropertyChanging("Replacement");
                _Replacement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Replacement");
                OnReplacementChanged();
            }
        }
        private global::System.String _Replacement;
        partial void OnReplacementChanging(global::System.String value);
        partial void OnReplacementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Options
        {
            get
            {
                return _Options;
            }
            set
            {
                OnOptionsChanging(value);
                ReportPropertyChanging("Options");
                _Options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Options");
                OnOptionsChanged();
            }
        }
        private global::System.String _Options;
        partial void OnOptionsChanging(global::System.String value);
        partial void OnOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsExpression
        {
            get
            {
                return _IsExpression;
            }
            set
            {
                OnIsExpressionChanging(value);
                ReportPropertyChanging("IsExpression");
                _IsExpression = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpression");
                OnIsExpressionChanged();
            }
        }
        private global::System.Boolean _IsExpression;
        partial void OnIsExpressionChanging(global::System.Boolean value);
        partial void OnIsExpressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSerialized
        {
            get
            {
                return _IsSerialized;
            }
            set
            {
                OnIsSerializedChanging(value);
                ReportPropertyChanging("IsSerialized");
                _IsSerialized = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSerialized");
                OnIsSerializedChanged();
            }
        }
        private global::System.Boolean _IsSerialized;
        partial void OnIsSerializedChanging(global::System.Boolean value);
        partial void OnIsSerializedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnabled
        {
            get
            {
                return _IsEnabled;
            }
            set
            {
                OnIsEnabledChanging(value);
                ReportPropertyChanging("IsEnabled");
                _IsEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnabled");
                OnIsEnabledChanged();
            }
        }
        private global::System.Boolean _IsEnabled;
        partial void OnIsEnabledChanging(global::System.Boolean value);
        partial void OnIsEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private global::System.DateTime _DateUpdated;
        partial void OnDateUpdatedChanging(global::System.DateTime value);
        partial void OnDateUpdatedChanged();

        #endregion

    
    }

    #endregion

    
}
