using System;

namespace x360ce.Engine.Win32
{
	[Flags]
	public enum CLSCTX
	{
		CLSCTX_INPROC_SERVER = 0x1,
		CLSCTX_INPROC_HANDLER = 0x2,
		CLSCTX_LOCAL_SERVER = 0x4,
		CLSCTX_REMOTE_SERVER = 0x10,
		CLSCTX_NO_CODE_DOWNLOAD = 0x400,
		CLSCTX_NO_CUSTOM_MARSHAL = 0x1000,
		CLSCTX_ENABLE_CODE_DOWNLOAD = 0x2000,
		CLSCTX_NO_FAILURE_LOG = 0x4000,
		CLSCTX_DISABLE_AAA = 0x8000,
		CLSCTX_ENABLE_AAA = 0x10000,
		CLSCTX_FROM_DEFAULT_CONTEXT = 0x20000,
		CLSCTX_INPROC = CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER,
		CLSCTX_SERVER = CLSCTX_INPROC_SERVER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER,
		CLSCTX_ALL = CLSCTX_SERVER | CLSCTX_INPROC_HANDLER
	}

}
