ALTER TABLE [dbo].[x360ce_Products]
    ADD CONSTRAINT [PK_x360ce_Products] PRIMARY KEY CLUSTERED ([ProductGuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

